### PR TITLE
Update gdal master

### PR DESCRIPTION
**Pull request by jakirkham**
Change the commit of the gdal submodule to match current `master` of the feedstock.

### CODE REVIEW

**Comment by jakirkham** [comment]
@ocefpaf @kmuehlbauer, I think this should fix the gdal issue.

**Comment by ocefpaf** [comment]
I think that should happen automatically, no?

**Comment by kmuehlbauer** [comment]
This points to the latest commit of the current gdal-master. Should be good then, @ocefpaf?

**Comment by jakirkham** [comment]
It's [crashing]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/127249877#L540-L542 ) on this feedstock. This is the best I can think of because it is probably trying to run `git pull`, which initiates a merge and failure. At least if I am understanding this failure correctly. There isn't much to go on here.

**Comment by jakirkham** [comment]
If it happens anyways, this should at least cause no issues to merge then even if it doesn't fix anything in the end, right?

**Comment by ocefpaf** [comment]
> This points to the latest commit of the current gdal-master. Should be good then, @ocefpaf?

In a way yes. I don't really known all the automation that @pelson created for the `feedstocks` repository, but I believe it should update itself and not require this PR. However, @jakirkham thinks this is needed go for it.

**Comment by jakirkham** [comment]
Well, the current commit listed here ( https://github.com/conda-forge/gdal-feedstock/commit/39342ed09404f3aa3981aa5d84c306a6819f8eae ) is for `gdal_1.x` and not `master`. I'm merely trying to reset this to `master` ( https://github.com/conda-forge/gdal-feedstock/commit/621f2b63670971e561085eb643005b47d8f2b0d7 ) so it can actually run `git pull`. Right now it is not a FF-merge, which will cause problems.

**Comment by jakirkham** [comment]
Not only that it is an non-FF-merge with conflicts so that would be the error we see.

**Comment by jakirkham** [comment]
I guess I'm not understanding why this commit is controversial. Could someone please clarify? I understand that some of us think it *should* work automatically, but it is not and hasn't been after several runs in the last hour. So, I would merely like to get things moving smoothly again. What can I do to convince everyone that this will not only help, but will do no harm?

**Comment by jakirkham** [comment]
Just as FYI, @pelson is out until Wednesday. So, if we are waiting for a response from him, things will stay broken for a couple days. Personally, I don't think that is acceptable. Especially for such a minor and straightforward change.

**Comment by ocefpaf** [comment]
> I guess I'm not understanding why this commit is controversial. Could someone please clarify?

I am not saying it is controversial. I am saying I don't know how feedstocks is supposed to work. I also already gave my :+1: to you in https://github.com/conda-forge/feedstocks/pull/5#issuecomment-216289141

**Comment by jakirkham** [comment]
Sorry, if I'm misunderstanding. That read to me as an uncertain response.

Could we try merging this if we are all on-board then? I'd like to to get the feedstocks script running again so we can starting handing out permissions to feedstocks. Right now that isn't happening due to this issue.

**Comment by ocefpaf** [comment]
> Sorry, if I'm misunderstanding. That read to me as an uncertain response.

I am uncertain. Still, since you seem to be on top of what happens here, I said: go for it :wink: 

I am in a meeting now BTW and I will need to do some day-job tasks after. Feel free to merge this once you think it is OK without waiting for me.

**Comment by jakirkham** [comment]
I don't have permissions. That's why I'm asking. 😉

**Comment by jakirkham** [comment]
For edification, this is the [line]( https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_feedstocks_submodules.py#L72 ) it crashes on so it is just running this `git submodule foreach git pull origin master`, which is the equivalent of `cd`-ing into each repo and running `git pull origin master`. Hence when it goes into `gdal`, it crashes because it cannot merge the aforementioned commits without [conflict]( https://github.com/conda-forge/gdal-feedstock/compare/gdal_1.x ).

**Comment by jakirkham** [comment]
> I am in a meeting now BTW and I will need to do some day-job tasks after. Feel free to merge this once you think it is OK without waiting for me.

Ok, get to it when you have time. I have tried to better explain the problem in the comment above.

**Comment by kmuehlbauer** [comment]
> For edification, this is the line it crashes on so it is just running this git submodule foreach git pull origin master, which is the equivalent of cd-ing into each repo and running git pull origin master. Hence when it goes into gdal, it crashes because it cannot merge the aforementioned commits without conflict.

This is exactly why I chimed in earlier in this thread. Also I have a strong feeling why this went wrong. The gdal_1.x branch was created and afterwards the gdal2 branch was renamed (or similar) to master. I'm not sure how @ocefpaf did it actually, but he obviously needed no commit. I think that only a commit would be detected by the feedstock's magic to have it point to latest master. So, if I'm correct, than a maintenance-commit to gdal-feedstock (master) also would help. But that's just a feeling.

@ocefpaf @jakirkham Can you follow? Does that make sense?

**Comment by ocefpaf** [comment]
> I don't have permissions. That's why I'm asking. 😉 

I though you had access to all repo in conda-forge.

**Comment by jakirkham** [comment]
I don't think you need to change anything with the gdal feedstock. We merely are going down the wrong branch here and once we change to the right branch everything should be fine.

**Comment by jakirkham** [comment]
Nope.

**Comment by ocefpaf** [comment]
@kmuehlbauer kind of make sense, but since this PR is here waiting let's give it a try.

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by jakirkham** [comment]
For the most part, it is not a big deal to not have access to everything. Most of the things I need access to I have. Though I guess it might be nice to have access to this repo in the future.

**Comment by jakirkham** [comment]
Just saw it added this commit ( https://github.com/conda-forge/feedstocks/commit/2cba812a8c88a8b7d376da85a74eb096441d4646 ). We are back on track guys. Thanks everyone.

**Comment by jakirkham** [comment]
Also, we are now [passing]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/127288635 ).

**Comment by pelson** [comment]
@jakirkham - I need to look into this. You should have access to everything - you are admin on conda-forge...

**Comment by ocefpaf** [comment]
> @jakirkham - I need to look into this. You should have access to everything - you are admin on conda-forge...

I assumed the same, but I guess there is still some tweaking we need to do on GitHub.

**Comment by jakirkham** [comment]
> @jakirkham - I need to look into this. You should have access to everything - you are admin on conda-forge...

Alright, let me know if I need to do anything.

Just as an example, I don't see edit buttons for the comments here. I guess if I am admin that would be different.

**Comment by pelson** [comment]
OK, I've definitely done this before, but it appears to have reverted (maybe the email got lost, and it times out?):

before:

before


after:

after

**Comment by jakirkham** [comment]
I believe you, @pelson. Not sure why it didn't work before, but it definitely works now. Got an email about it and seem to have permissions on everything.

**Comment by jakirkham** [comment]
Thanks for looking into it, @pelson.

**Pull request merged**
