### PR TITLE
update openvisus package recipe

### PR DESCRIPTION
**Pull request by spetruzza**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @spetruzza! 😄

@isuruf @beckermr, do you know why this would not have been updated by the bot?

**Comment by beckermr** [comment]
No idea. The bot can be flaky for sure.

**Comment by jakirkham** [comment]
Do you know where we can see the relevant webhook? Asking as I know things moved around somewhat recently 🙂

**Comment by spetruzza** [comment]
I am not sure how things should get updated on feedstocks. I just noticed that on conda-forge there was not the latest version of this package, so I started updating this: https://github.com/conda-forge/openvisus-feedstock/

which currently have issues on the CI build. Please let me know if I should fix that first, or things should work differently.

Also, we push this same package on another channel called "visus", where we have the latest version (if that helps).

**Comment by jakirkham** [comment]
Thanks for the info. 🙂

Yeah this repo is meant to be automatically updated. So shouldn't require intervention. That said, obviously things are not working in this case. Thanks for pointing that out! 😄

We are just now trying to figure out why that is. So we can get things working again. 😉

**Comment by jakirkham** [comment]
@isuruf, do you know how we would retriever the org webhook for this?

**Comment by isuruf** [comment]
It's buried somewhere in https://github.com/organizations/conda-forge/settings/hooks/179590406

**Comment by jakirkham** [comment]
Thanks. I dug in and found it. Gave it a couple prods, but didn't see anything new show up.

**Comment by jakirkham** [comment]
So I pulled feedstocks locally to see if I was missing anything. Turns out this already got updated ( https://github.com/conda-forge/feedstocks/commit/c30698f2dcb78b163ef48739e773afcc9e348efb ).

@spetruzza, could you please trying pulling again locally and make sure you are seeing this update as well? 🙂

**Comment by jakirkham** [comment]
Thanks again @spetruzza. As this change is already in `feedstocks`, have closed this out. Please let us know if you are still having trouble. Happy to help out 🙂

**Pull request closed without merging**
