### PR TITLE
Removed miktex-portable

### PR DESCRIPTION
**Pull request by jakirkham**
Remove miktex-portable as the feedstock was deleted.

### CODE REVIEW

**Comment by jakirkham** [comment]
@ocefpaf, could you please merge. This should resolve feedstocking failures like the one shown in this [log]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/127234035 ).

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by jakirkham** [comment]
Restarted the feedstock generation build.

**Comment by jakirkham** [comment]
Doesn't quite fix it. Something is off with `gdal` here.

**Comment by kmuehlbauer** [comment]
@jakirkham Me and @ocefpaf worked on gdal-feedstock and switched gdal2 to master and the former master to gdal_1.x.

The feedstocks submodule points to the gdal_1.x branch. I do not know if this is the source of this behaviour.

**Comment by jakirkham** [comment]
When was this roughly? These failures started about an hour ago.

**Comment by kmuehlbauer** [comment]
Two hours ago, roundabout.

**Comment by jakirkham** [comment]
Ah, sorry, I forget the failure 3 hours ago was a rate limiting issue. So, yeah that could be the problem.

**Comment by jakirkham** [comment]
I think this PR ( https://github.com/conda-forge/feedstocks/pull/5 ) might fix it then. Please check to make sure I did in fact get the correct commit for `master` on the gdal feedstock.

**Pull request merged**
